version: "3"
services:
  
  ui:
   build:
      context: ./ui
      dockerfile: Dockerfile.dev
   ports:
    -  8080:8080
   container_name: adlin-meeting-ui
   networks:
    -  adlin-meeting-net
   volumes:
    -  ./ui/src:/usr/app/src
    -  ./ui/public:/usr/app/public
   depends_on:
    - api
   stdin_open: true
   tty: true

  api:
   build:
      context: ./api
      dockerfile: Dockerfile.dev
   ports:
     - 3080:3080
   container_name: adlin-meeting-api
   networks:
     - adlin-meeting-net
   volumes:
    - ./api/src:/usr/app/src
   env_file:
      - ./api/.env
   depends_on:
    - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - adlin-meeting-net
    volumes:
      - mongo-data:/data/db

networks:
  adlin-meeting-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local