name: '' #set whatevername you want to your github job
on: {} # set the events you would like to trigger this job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: adlin-meeting #set the whatever name you want to this step
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0  # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          docker_compose_file: '../../docker-compose.yaml' # set the path to the folder where the docker-compose file is located
          heroku_apps: '[{"imagename":"ui","appname":"ui","apptype":"web"},{"imagename":"api","appname":"api","apptype":"api"},{"imagename":"db","appname":"db","apptype":"database"}]' # List of Docker Image name, Heroku app and Heroku app type